server:
  port: 1213
eureka:
  instance:
    prefer-ip-address: true
spring:
  application:
    name: fornecedor-api
  datasource:
    driverClassName: org.postgresql.Driver
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create